### PR TITLE
Http content-type negotiation

### PR DESCRIPTION
**Pull request by deadtrickster**
New HTTP contrib function for content negotiation.

### CODE REVIEW

**Comment by deadtrickster** [comment]
ping @yurrriq

**Comment by yurrriq** [comment]
I'll take a look this weekend.

**Comment by deadtrickster** [comment]
I extracted the code to https://github.com/deadtrickster/accept. I believe the code is good enough to be (re)usable.

**Comment by yurrriq** [comment]
Cool. Is there an RFC (section) to check against?

**Comment by deadtrickster** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by deadtrickster** [comment]
Initially I ported this code: https://bitbucket.org/ww/goautoneg/. It is used by Prometheus server but I shortly found that examples from RFC do not work :confused:

**Comment by yurrriq** [comment]
I didn't get to it this weekend and have a busy week/end coming up. Don't let me slow you down.

**Comment by yurrriq** [comment]
After a cursory glance, this looks great, especially the accept repo.

**Comment by deadtrickster** [comment]
Awesome thanks. I'm closing this.

**Pull request closed without merging**
