### PR TITLE
test erlang 21, 22

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by getong** [comment]
The AppVeyor build failed, but travis-ci and coverage build are all passed. not know why.

**Comment by deadtrickster** [comment]
Hi, usually when gpb_plugin updated erlang files need to be regenerated.

**Comment by getong** [comment]
If the plugin does not need to update, I can reset it. But I think it does make sense.

**Comment by deadtrickster** [comment]
I mean you can regenerate the code along the way

**Comment by getong** [comment]
I don’t know. What cmd I need to type?

**Comment by marco-m** [comment]
Hello what is the status of this PR ? Thanks!

**Comment by benoitc** [comment]
> Hello what is the status of this PR ? Thanks!

same question...

**Pull request closed without merging**
