### PR TITLE
update rebar3_plugin to 1.7.3 and regenerate model

### PR DESCRIPTION
**Pull request by deadtrickster**
OK tabs are because of `defs_as_proplists`. Need to investigate more

### CODE REVIEW

**Comment by deadtrickster** [comment]
https://github.com/tomas-abrahamsson/gpb/blob/dde495ce3dcd4a58d55fdcaee8f2a18617b366b1/src/gpb_compile.erl#L5340

**Comment by deadtrickster** [comment]
Ok, Elvis not complaining because src/model not presented in it's config: https://github.com/deadtrickster/prometheus.erl/blob/master/elvis.config#L12

**Comment by yurrriq** [comment]
:+1: `skip_comments` appears to be deprecated btw. Check the Elvis wiki.

**Comment by deadtrickster** [comment]
Do you have a link for this? Can't find it myself.

**Comment by yurrriq** [comment]
https://github.com/inaka/elvis_core/wiki/Rules#line-length

**Comment by deadtrickster** [comment]
still in the code! https://github.com/inaka/elvis_core/blob/88370e29526a27241acdb52a6f9a026a6685fcd9/src/elvis_style.erl#L188

I think they just forgot to mention it. But our comments are less than 80 chars anyway, right?

**Comment by yurrriq** [comment]
After a little work they are, yeah. IME `skip_comments` didn't seem to do anything 😕

**Pull request merged**
