### PR TITLE
Add a collector for distribution related metrics

### PR DESCRIPTION
**Pull request by essen**
This is a work in progress for a new collector for distribution related metrics. This collector should be useful to explore distribution issues and was created to debug RabbitMQ issues. It has not yet been battle tested so some metrics may be added later on.

As RabbitMQ must support TLS distribution as well I will also add support for it. I have not started on that yet. I will also provide a description for the various metrics as they're currently entirely missing.

/cc @gerhard

### CODE REVIEW

**Comment by gerhard** [comment]
Building a Docker image and running it part of rabbitmq_prometheus now.

**Comment by gerhard** [comment]
I'm getting the same failures when running `make tests` in rabbitmq_prometheus as the CI.

```shell
== rabbit_prometheus_http_SUITE ==

  * [default_config]

== rabbit_prometheus_http_SUITE ==

  * [config_port]
    get_test (00:00.036)
    content_type_test (00:00.057)
    encoding_test (00:00.019)
  * [config_port]
=INFO REPORT==== 7-May-2019::14:20:18.036093 ===
    application: inets
    exited: stopped
    type: temporary

  * [with_metrics]


rabbit_prometheus_http_SUITE > default_config
    {skip,"Failed to initialize RabbitMQ"}

rabbit_prometheus_http_SUITE > config_path
    {skip,"Failed to initialize RabbitMQ"}

rabbit_prometheus_http_SUITE > with_metrics
    {'EXIT',
        {badarg,
            [{lists,keysearch,
                 [rmq_nodes,1,{skip,"Failed to initialize RabbitMQ"}],
                 []},
             {test_server,lookup_config,2,
                 [{file,"test_server.erl"},{line,1547}]},
             {rabbit_ct_broker_helpers,get_node_config,2,
                 [{file,"src/rabbit_ct_broker_helpers.erl"},{line,997}]},
             {rabbit_ct_broker_helpers,get_node_config,3,
                 [{file,"src/rabbit_ct_broker_helpers.erl"},{line,1012}]},
             {rabbit_prometheus_http_SUITE,init_per_group,2,
                 [{file,"test/rabbit_prometheus_http_SUITE.erl"},{line,77}]},
             {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1562}]},
             {test_server,run_test_case_eval1,6,
                 [{file,"test_server.erl"},{line,1165}]},
             {test_server,run_test_case_eval,9,
                 [{file,"test_server.erl"},{line,1012}]}]}}
```

How do we get this to work on a single Erlang node?

**Comment by gerhard** [comment]
`pivotalrabbitmq/rabbitmq-prometheus:3.8.0-alpha.646-2019.05.07` has this collector baked in. I have only been exploring the metrics in Grafana, haven't built any dashboards yet. Looking good so far:

```
# TYPE erlang_vm_dist_recv_oct_bytes gauge
# HELP erlang_vm_dist_recv_oct_bytes TODO
erlang_vm_dist_recv_oct_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 17316769
erlang_vm_dist_recv_oct_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 13675640
# TYPE erlang_vm_dist_recv_cnt gauge
# HELP erlang_vm_dist_recv_cnt TODO
erlang_vm_dist_recv_cnt{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 13426
erlang_vm_dist_recv_cnt{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 13022
# TYPE erlang_vm_dist_recv_max_bytes gauge
# HELP erlang_vm_dist_recv_max_bytes TODO
erlang_vm_dist_recv_max_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 28671
erlang_vm_dist_recv_max_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 25422
# TYPE erlang_vm_dist_recv_avg_bytes gauge
# HELP erlang_vm_dist_recv_avg_bytes TODO
erlang_vm_dist_recv_avg_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 1289
erlang_vm_dist_recv_avg_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 1050
# TYPE erlang_vm_dist_recv_dvi_bytes gauge
# HELP erlang_vm_dist_recv_dvi_bytes TODO
erlang_vm_dist_recv_dvi_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 443
erlang_vm_dist_recv_dvi_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 270
# TYPE erlang_vm_dist_send_oct_bytes gauge
# HELP erlang_vm_dist_send_oct_bytes TODO
erlang_vm_dist_send_oct_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 993644
erlang_vm_dist_send_oct_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 960344
# TYPE erlang_vm_dist_send_cnt gauge
# HELP erlang_vm_dist_send_cnt TODO
erlang_vm_dist_send_cnt{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 17081
erlang_vm_dist_send_cnt{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 16659
# TYPE erlang_vm_dist_send_max_bytes gauge
# HELP erlang_vm_dist_send_max_bytes TODO
erlang_vm_dist_send_max_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 3712
erlang_vm_dist_send_max_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 679
# TYPE erlang_vm_dist_send_avg_bytes gauge
# HELP erlang_vm_dist_send_avg_bytes TODO
erlang_vm_dist_send_avg_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 58
erlang_vm_dist_send_avg_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 57
# TYPE erlang_vm_dist_send_pend_bytes gauge
# HELP erlang_vm_dist_send_pend_bytes TODO
erlang_vm_dist_send_pend_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 0
erlang_vm_dist_send_pend_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 0
# TYPE erlang_vm_dist_port_input_bytes gauge
# HELP erlang_vm_dist_port_input_bytes TODO
erlang_vm_dist_port_input_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 17263024
erlang_vm_dist_port_input_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 13623511
# TYPE erlang_vm_dist_port_output_bytes gauge
# HELP erlang_vm_dist_port_output_bytes TODO
erlang_vm_dist_port_output_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 44
erlang_vm_dist_port_output_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 44
# TYPE erlang_vm_dist_port_memory_bytes gauge
# HELP erlang_vm_dist_port_memory_bytes TODO
erlang_vm_dist_port_memory_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 44
erlang_vm_dist_port_memory_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 44
# TYPE erlang_vm_dist_port_queue_size gauge
# HELP erlang_vm_dist_port_queue_size TODO
erlang_vm_dist_port_queue_size{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 0
erlang_vm_dist_port_queue_size{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 0
# TYPE erlang_vm_dist_proc_memory_bytes gauge
# HELP erlang_vm_dist_proc_memory_bytes TODO
erlang_vm_dist_proc_memory_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 16704
erlang_vm_dist_proc_memory_bytes{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 16704
# TYPE erlang_vm_dist_proc_heap_size_words gauge
# HELP erlang_vm_dist_proc_heap_size_words TODO
erlang_vm_dist_proc_heap_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 1598
erlang_vm_dist_proc_heap_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 1598
# TYPE erlang_vm_dist_proc_min_heap_size_words gauge
# HELP erlang_vm_dist_proc_min_heap_size_words TODO
erlang_vm_dist_proc_min_heap_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 233
erlang_vm_dist_proc_min_heap_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 233
# TYPE erlang_vm_dist_proc_min_bin_vheap_size_words gauge
# HELP erlang_vm_dist_proc_min_bin_vheap_size_words TODO
erlang_vm_dist_proc_min_bin_vheap_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 46422
erlang_vm_dist_proc_min_bin_vheap_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 46422
# TYPE erlang_vm_dist_proc_stack_size_words gauge
# HELP erlang_vm_dist_proc_stack_size_words TODO
erlang_vm_dist_proc_stack_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 12
erlang_vm_dist_proc_stack_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 12
# TYPE erlang_vm_dist_proc_total_heap_size_words gauge
# HELP erlang_vm_dist_proc_total_heap_size_words TODO
erlang_vm_dist_proc_total_heap_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 1974
erlang_vm_dist_proc_total_heap_size_words{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 1974
# TYPE erlang_vm_dist_proc_message_queue_len gauge
# HELP erlang_vm_dist_proc_message_queue_len TODO
erlang_vm_dist_proc_message_queue_len{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 0
erlang_vm_dist_proc_message_queue_len{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 0
# TYPE erlang_vm_dist_proc_reductions gauge
# HELP erlang_vm_dist_proc_reductions TODO
erlang_vm_dist_proc_reductions{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3"} 43478
erlang_vm_dist_proc_reductions{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2"} 43481
# TYPE erlang_vm_dist_proc_status untyped
# HELP erlang_vm_dist_proc_status TODO
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3",status="exiting"} 0
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3",status="garbage_collecting"} 0
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3",status="waiting"} 1
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3",status="running"} 0
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3",status="runnable"} 0
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3",status="suspended"} 0
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2",status="exiting"} 0
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2",status="garbage_collecting"} 0
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2",status="waiting"} 1
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2",status="running"} 0
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2",status="runnable"} 0
erlang_vm_dist_proc_status{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2",status="suspended"} 0
# TYPE erlang_vm_dist_node_state untyped
# HELP erlang_vm_dist_node_state TODO
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3",state="pending"} 0
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3",state="up"} 1
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq3",state="up_pending"} 0
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2",state="pending"} 0
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2",state="up"} 1
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbit@rabbitmq1",peer="rabbit@rabbitmq2",state="up_pending"} 0
```

**Comment by essen** [comment]
Let's plan for a few hours next Tuesday to do the dashboard.

**Comment by gerhard** [comment]
@essen I was trying to find a better way of representing `erlang_vm_dist_node_state` and the conclusion is that we will need to map states to different values, e.g.

```
0 -> pending
1 -> up_pending
2 -> up
```

In other words:

```
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbitmq_prometheus",peer="rabbit@rabbitmq2",state="pending"} 0
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbitmq_prometheus",peer="rabbit@rabbitmq2",state="up"} 1
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbitmq_prometheus",peer="rabbit@rabbitmq2",state="up_pending"} 0
```

Becomes:

```
erlang_vm_dist_node_state{node="rabbit@rabbitmq1",cluster="rabbitmq_prometheus",peer="rabbit@rabbitmq2"} 2
```

This is because distribution link between node **rabbit@rabbitmq1** and peer **rabbit@rabbitmq2** is `up`.

Same for `erlang_vm_dist_proc_status`.

**Comment by essen** [comment]
Ah good, yes that's perfect. I will do the change next week. I will also do the minor change of removing `_oct` to avoid repeating ourselves with `bytes`.

**Comment by essen** [comment]
All good and ready for review @deadtrickster 

Note that there's some additional information I would like to extract from OTP that is seemingly not possible currently (?) so expect some additional work on this collector in the long term.

**Comment by deadtrickster** [comment]
Thanks! do you have a dashboard for this?

**Comment by deadtrickster** [comment]
https://hex.pm/packages/prometheus/4.4.0

**Comment by gerhard** [comment]
> Do you have a dashboard for this?

[Yes](https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/docker/grafana/dashboards/Erlang-Distribution.json). There is a newer version which has not been committed yet. I want to share it via grafana.com when the first version is done.

All Grafana dashboards will be available via HTTP from the `rabbitmq_prometheus` plugin itself, e.g. `/grafana/erlang-distribution.json`. This enables generating [RabbitMQ-Overview](https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/docker/grafana/dashboards/RabbitMQ-Overview.json) based on RabbitMQ config - think thresholds.

**Comment by gerhard** [comment]
FYI [ERL-959: Distribution inet send_cnt & recv_cnt reports incorrect values](https://bugs.erlang.org/browse/ERL-959)

**Comment by gerhard** [comment]
Last week it became clear that exposing Grafana dashboards via HTTP from the `rabbitmq_prometheus` plugin is not a good idea. The biggest issue is that thresholds are going to be deployment specific, so a single Grafana dashboard for all RabbitMQ metrics would not work with this approach. I'm settling on having these dashboards shared via grafana.com, which seems to be the easiest approach.

**Comment by deadtrickster** [comment]
Is this dashboard really RabbitMQ specific? If not really I would love to have it in https://github.com/deadtrickster/beam-dashboards :-) :blush:

**Comment by essen** [comment]
It's not RabbitMQ-specific at all.

**Comment by gerhard** [comment]
It currently lives here: [rabbitmq/rabbitmq-prometheus/docker/grafana/dashboards/Erlang-Distribution.json](https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/docker/grafana/dashboards/Erlang-Distribution.json).

It's still WIP, but once we tag v3.8.0, it will be worth adding to **beam-dashboards** 😉

**Comment by gerhard** [comment]
This Grafana dashboard is now public: https://grafana.com/grafana/dashboards/11352

image

**Pull request merged**
