### PR TITLE
Added GH Action

### PR DESCRIPTION
**Pull request by vkatsuba**
**Purposes of changes:**
* Provided base GitHub Actions
* Added `coveralls`: used fork till merge/release https://github.com/markusn/coveralls-erl/pull/36
* Added `elvis` call to GH Actions
* Updated `README.md`: added GH Badges
* Remove `.travis.yml`
* Update `rebar.config.script` based on GH Actions
* Add `rebar3` to `.gitignore`
* Fix error for GH Action when tests running - `{'EXIT',nodistribution}`
* Fix `dialyzer` warning:
```erlang
src/metrics/prometheus_quantile_summary.erl
 307: The created fun has no local return
 346: The created fun has no local return
 487: Function quantile_merge/2 has no local return
 491: Record construction #quantile_estimator{samples_count::number(),data_count::'undefined',inserts_since_compression::'undefined',data::[#group{v::number(),g::number(),delta::number(),rank::number()}],invariant::fun()} violates the declared type of field data_count::number() and inserts_since_compression::number()
```

**GH Action Result:** https://github.com/vkatsuba/prometheus.erl/actions/runs/788619303

### CODE REVIEW

**Comment by deadtrickster** [comment]
Great! could you please include elvis too?

**Comment by vkatsuba** [comment]
> could you please include elvis too?

Done.

**Comment by deadtrickster** [comment]
I just noticed a few changed unrelated to GH actions:
src/metrics/prometheus_quantile_summary.erl
test/eunit/collectors/vm/prometheus_vm_dist_collector_tests.erl

would be great to have them in a separate MR with short description, so I can proceed with this MR. Thanks!

**Comment by vkatsuba** [comment]
> I just noticed a few changed unrelated to GH actions:
> 
> src/metrics/prometheus_quantile_summary.erl
> 
> test/eunit/collectors/vm/prometheus_vm_dist_collector_tests.erl
> 
> 
> 
> would be great to have them in a separate MR with short description, so I can proceed with this MR. Thanks!

The changes is related to dialyzer warnings. The dialyzer is a part of checking in GH Actions. I can remove it but I will also need to remove dialyzer call. Just for notes.

**Comment by vkatsuba** [comment]
In other words all changes in current PR is repeated to GH actions and for test/checking passing in containers.

**Comment by vkatsuba** [comment]
@deadtrickster I was divided to separate commits with short description. As I wrote above, they all refer to the current PR. So, please take a look if this approach with dividing commits is suite for you.

**Pull request merged**
