### PR TITLE
Make rebar3_archive_plugin coditional on rebar3

### PR DESCRIPTION
**Pull request by NikolaBorisov**
This would make the project rebar2 compatible.

### CODE REVIEW

**Comment by NikolaBorisov** [comment]
Fixes #111

**Comment by NikolaBorisov** [comment]
@deadtrickster @essen Please let me know if I need to change anything?

**Comment by essen** [comment]
I was hoping that @deadtrickster could review it since I'm not a rebar user. But tomorrow I will test and merge it if nobody does it before.

**Review by essen — APPROVED** [review]

**Comment by essen** [comment]
Please rebase to current master.

**Comment by NikolaBorisov** [comment]
@essen Done.

**Comment by NikolaBorisov** [comment]
@essen I don't know why the build is failing ;( It worked before I rebased..

**Comment by essen** [comment]
Travis eunit tests are failing, any idea why?

**Comment by essen** [comment]
OK. Well I can't merge if that fails unfortunately. :-) If you can investigate that would help.

**Comment by NikolaBorisov** [comment]
> OK. Well I can't merge if that fails unfortunately. :-) If you can investigate that would help.

@essen, I think somehow the master branch build is also broken. You can try to trigger build on the master branch and see if it breaks. My best guess is something changed with rebar3 the build always downloads the latest version of rebar3. 

I figured out how to fix the build and made a second commit to fix it.

**Comment by essen** [comment]
Thanks. Apparently I can only "Squash and merge" so I'll do that and @deadtrickster can sue me if there's a problem.

**Pull request merged**
