### PR TITLE
Use latest rebar3 and persist its cache

### PR DESCRIPTION
**Pull request by yurrriq**
... on Travis, that is. Depends on #9, but could easily be rebased, as needed.

### CODE REVIEW

**Comment by yurrriq** [comment]
This Travis error looks like a race condition. I've seen something similar once in a while locally too.

**Comment by deadtrickster** [comment]
fixed travis error here: https://github.com/deadtrickster/prometheus.erl/commit/a4f1a5e22e44288931869f1b98c9a13f8082da8b. 

I think we should merge #9 first and rebase (yeah I love rebase :smiling_imp:).

**Comment by yurrriq** [comment]
Rebased on #9.

**Comment by yurrriq** [comment]
Rebased on master.

**Comment by deadtrickster** [comment]
:+1:

**Pull request merged**
