### PR TITLE
Support Erlang 23 format for blocks entry in allocators

### PR DESCRIPTION
**Pull request by dcorbacho**
`blocks_size` has been removed, instead the `count` and `size` info is provided in `blocks`

```
{blocks,[{ll_alloc,[{count,1,1,1},{size,131144,131144,131144}]}]}
```

### CODE REVIEW

**Comment by deadtrickster** [comment]
as far as I can tell it's meant to be backwards compatible, right? Also build fails

**Comment by essen** [comment]
Yes that's what I meant, it's backward compatible. And yes, build fails. :-)

**Comment by dcorbacho** [comment]
Thank you both, it's fixed now. I hadn't compiled it independently from rabbit..

**Comment by deadtrickster** [comment]
still red :-(

**Comment by essen** [comment]
Coverage necessarily decreases because the new code will only run in OTP 23.

**Comment by deadtrickster** [comment]
Thanks!

**Comment by gerhard** [comment]
I am finally catching up on this. I've noticed that v4.5.0, the latest release currently available, [does not include this change](https://github.com/deadtrickster/prometheus.erl/compare/v4.5.0...f9c7a221b280577c9a1a5fb6c036d72d2dfb9390).

If this is backwards-compatible with OTP 22 & 21, are we waiting for anything else before we cut a new release? There is no rush from my perspective, just wondering.

**Pull request merged**
